version: '2'
services:
  postfix:
    image: postfix/postfix:latest
    expose:
    - "25"
    env_file:
      - .env
    restart: always
    volumes:
     - "/etc/localtime:/etc/localtime:ro"
     - "./transport:/etc/postfix/transport"
     
